config/routes.rb
Rails.application.routes.draw do
# resources :contacts, only: [:index, :new, :create, :destroy]
devise_for :users

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # page for the commissions-view
  get "commissions", to: "pages#commissions"
    # page for the commissions-view
  get "renewals", to: "pages#renewals"
  # page for the commissions-view
  get "claims", to: "pages#claims"
  # integrating routes to notes
  get "notes", to: "pages#notes"
  post 'notes', to: "notes#create"
  # integrating contacts
  # get 'contacts', to: 'contacts#create'
  get 'contacts', to: 'contacts#new'
  post 'contacts', to: 'contacts#create'

  # integrating routes to services
  get 'service_analytics', to: "pages#service_data_analytics", as: :analytics
  get 'service_audit', to: "pages#service_audit", as: :audit
  get 'service_integration', to: "pages#service_data_integration", as: :integration

  # website landing page (home), dashboard (index) [and not yet active (show)]
  resources :pages, only: [:index, :show, :home] do
    collection do
      post 'share_page_with_options'
    end
  end

  # resources :users, only: [:new, :create, :destroy]
  resources :accounting_data, only: [:new, :create, :index, :destroy] do
    collection {post :import}
  end

  # file upload section
  resources :file_uploads, only: [:index, :new, :create, :destroy]

  #international client section
  resources :international_clients, only: [:new, :create, :destroy]

  # integrating routes to notes
  # resources :notes, only [:store, :new, :create, :destroy, :update]
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  NETWORKS = ["Lianz", "Nerali", "Swissy", "AG & Co"]
  YEARS = [Time.now.year - 3, Time.now.year - 2, Time.now.year - 1, Time.now.year]
  QUARTERS = [1, 2, 3, 4]

  belongs_to :user
  has_many :accounting_data, dependent: :destroy

  validates :reinsurance_network, presence: true, inclusion: { in: NETWORKS }
  validates :balance_year, presence: true, inclusion: { in: YEARS }
  validates :quarter, presence: true, inclusion: { in: QUARTERS }
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  def create
    @file_upload = FileUpload.new(file_upload_params)
    @file_upload.user = current_user
    # authorize @file_upload
    if @file_upload.save
      respond_to do |format|
        format.html { redirect_to new_file_upload_path }
        # format.js
      end
    else
      render :new
    end
  end

  def new
    @file_upload = FileUpload.new
  end

  def index
    @file_uploads = FileUpload.all
  end

  def destroy
    # @user = current_user
    # authorize @user
    @file_upload = FileUpload.find(params[:id])
    @file_upload.destroy
    redirect_to new_file_upload_path
  end

  private

  def file_upload_params
    params.require(:file_upload).permit(:reinsurance_network, :balance_year, :quarter, :file_name)
  end
end

app/views/file_uploads/_upload_modal.html.erb
<div id="upload-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div>
        <h4>and now import your file</h4>
        <%= form_tag import_accounting_data_path, multipart: true do %>
          <%= file_field_tag :file %>
          <%= submit_tag "Import CSV", class: "btn btn-yellow" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/file_uploads/create.html.erb
<h1>FileUploads#create</h1>
<p>Find me in app/views/file_uploads/create.html.erb</p>

app/views/file_uploads/create.js.erb
$('#upload-file').html("<%= j render 'upload_modal' %>");
$('#upload-modal').modal('create');

app/views/file_uploads/destroy.html.erb
<h1>FileUploads#destroy</h1>
<p>Find me in app/views/file_uploads/destroy.html.erb</p>

app/views/file_uploads/index.html.erb
<h1>FileUploads#index</h1>
<p>Find me in app/views/file_uploads/index.html.erb</p>

app/views/file_uploads/new.html.erb
  <div class="container container-upload">
    <div class="container-form">
      <h1>Data Uploader</h1>
      <%= simple_form_for @file_upload, remote: true do |f| %>
        <%= f.input :reinsurance_network, collection: FileUpload::NETWORKS, :label => "Select the Reinsurance Network" %>
        <%= f.input :balance_year, collection: FileUpload::YEARS, :label => "Select the Balance Year" %>
        <%= f.input :quarter, collection: FileUpload::QUARTERS, :label => "Select the Quarter" %>
        <%= f.input :file_name, :label => "Any additional comment?" %>
        <div data-toggle="modal" data-target="#exampleModal">
          <%= f.button :submit, :value => "Choose file", class: "btn-yellow" %>
        </div>
      <% end %>
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Choose the file to import</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div>
                <%= form_tag import_accounting_data_path, multipart: true do %>
                  <%= file_field_tag :file %>
                  <%= submit_tag "Import CSV", class: "btn btn-yellow" %>
                <% end %>
              </div>
            </div>
            <div class="modal-footer">
            </div>
          </div>
        </div>
      </div>
    <!--   <p><%= link_to "View ALL uploaded data", accounting_data_path, class: "btn-yellow" %></p>
      <p><%= link_to "Back to dashboard", pages_path, class: "btn-yellow" %></p>
     -->
      <h2>Latest uploads</h2>
      <table>
        <tbody class="align-left">
          <% FileUpload.last(5).reverse.each do |file_upload| %>
            <tr>
              <td><%= file_upload.created_at %></td>
              <td>|</td>
              <td><%= file_upload.reinsurance_network %></td>
              <td><%= file_upload.balance_year %></td>
              <td>Q<%= file_upload.quarter %></td>
              <td><%= file_upload.file_name %></td>
              <td>by <%= file_upload.user.first_name %></td>
              <td></td>
              <td><% if current_user.id == file_upload.user_id %>
                <%= link_to file_upload_path(file_upload.id), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash"></i>
                <% end %>
              <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>