config/routes.rb
Rails.application.routes.draw do
# resources :contacts, only: [:index, :new, :create, :destroy]
devise_for :users

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # page for the commissions-view
  get "commissions", to: "pages#commissions"
    # page for the commissions-view
  get "renewals", to: "pages#renewals"
  # page for the commissions-view
  get "claims", to: "pages#claims"
  # integrating routes to notes
  get "notes", to: "pages#notes"
  post 'notes', to: "notes#create"
  # integrating contacts
  # get 'contacts', to: 'contacts#create'
  get 'contacts', to: 'contacts#new'
  post 'contacts', to: 'contacts#create'

  # integrating routes to services
  get 'service_analytics', to: "pages#service_data_analytics", as: :analytics
  get 'service_audit', to: "pages#service_audit", as: :audit
  get 'service_integration', to: "pages#service_data_integration", as: :integration

  # website landing page (home), dashboard (index) [and not yet active (show)]
  resources :pages, only: [:index, :show, :home] do
    collection do
      post 'share_page_with_options'
    end
  end

  # resources :users, only: [:new, :create, :destroy]
  resources :accounting_data, only: [:new, :create, :index, :destroy] do
    collection {post :import}
  end

  # file upload section
  resources :file_uploads, only: [:index, :new, :create, :destroy]

  #international client section
  resources :international_clients, only: [:new, :create, :destroy]

  # integrating routes to notes
  # resources :notes, only [:store, :new, :create, :destroy, :update]
end

app/views/shared/_container_dashboard.html.erb
<div class="container-dashboard" id="dashboard-area">

  <div class="container-top">

    <div id="sortableKpi" class="container-left">
      <div class="card-kpi">
        <a href="<%= commissions_path %>">
          <p class="kpi-title">Commissions Ratio:  <%= number_to_percentage(@commission_ratio, precision: 2) %></p>
        </a>
        <div class="container-kpi">
          <canvas id="kpiCommissions" data-years="<%= @data_process.map { |k, v| k  }.sort.to_json %>" data-process-json="<%= @data_process.map{ |k, v| v[:reins_comm_ratio][:value] }.to_json %>"></canvas>
        </div>
      </div>
      <div class="card-kpi">
        <a href="<%= claims_path %>">
          <p class="kpi-title">Claims Ratio:  <%= number_to_percentage(@claim_ratio , precision: 2) %></p>
        </a>
        <div class="container-kpi">
          <canvas id="kpiClaims" data-years="<%= @data_process.map { |k, v| k  }.sort.to_json %>" data-process-json="<%= @data_process.map{ |k, v| v[:claim_ratio][:value] }.to_json %>"></canvas>
        </div>
      </div>
      <div class="card-kpi">
        <a href="#">
          <p class="kpi-title">Balance Ratio:  <%= number_to_percentage(@balance_ratio, precision: 2) %></p>
        </a>
        <div class="container-kpi">
          <canvas id="kpiBalance" data-years="<%= @data_process.map { |k, v| k  }.sort.to_json %>" data-process-json="<%= @data_process.map{ |k, v| v[:balance_ratio][:value] }.to_json %>"></canvas>
        </div>
      </div>
    </div>

    <div class="container-right">
      <div class="container-table">
        <div class="card-table">
          <table>
            <tbody>
              <tr>
                <th scope="col" >  Accounting Item</th>
                <% @data_process.sort.each do |k, v| %>

                <th class="by"> <%= k %> </th>

                <% end %>
              </tr>

              <% AccountingDatum.attributes_keys.each do |key| %>
                <tr>
                  <th scope="row"> <%= @data_process.first[1][key][:label].to_s %></th>
                   <% @data_process.each do |k, v| %>
                       <td> <%= number_with_precision(v[key][:value], precision: 2, separator: '.', delimiter: ',') %> </th>
                  <% end %>
                </tr>
              <% end  %>

            </tbody>
          </table>
        </div>
      </div>
        <div id="sortableCharts" class="container-chart">
          <div class="card-chart">
            <div class="card-chart-img">
            </div>
            <div class="card-chart-text">
              Premium
              <canvas id="premiumChart"  data-years="<%= @data_process.map { |k, v| k  }.sort.to_json %>" data-process-json="<%= @data_process.map{ |k, v| v[:premium][:value] }.to_json %>">    </canvas>
            </div>
          </div>
          <div class="card-chart">
            <div class="card-chart-img">
            </div>
            <div class="card-chart-text">
              Balance
              <canvas id="balanceChart" data-years="<%= @data_process.map { |k, v| k  }.sort.to_json %>" data-process-json="<%= @data_process.map{ |k, v| v[:balance][:value] }.to_json %>"></canvas>
            </div>
          </div>
        </div>
    </div>

  </div>

    <div class="container-bottom">
      <div class="card-news">
        <h3>Latest News</h3>
        <%= link_to "Sanctions Notice - Venezuela", "https://www.gfsc.gg/news/article/sanctions-notice-venezuela-4"%>
        <p>"Council Regulation (EU) No 2017/2063, as implemented in the Bailiwick by the Venezuela (Restrictive Measures) (Guernsey) Ordinance, [...]"</p>
      </div>

    </div>

</div>

app/views/shared/_container_dashboard_claims.html.erb
<div class="container-dashboard" id="dashboard-area">
  <div class="container-top">
    <div class="container-left">
      <div class="card-survey">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <div class="card-chart-text">
          <%= render 'shared/note' %>
        </div>
      </div>
    </div>

    <div class="container-right  d-flex">
      <div class="card-chart">
        <div class="card-chart-text">
          Claims Paid
          <canvas id="ClaimPaid" width="400" height="400" data-years="<%= @data_process.map { |k, v| k  }.sort.to_json %>" data-process-json="<%= @data_process.map{ |k, v| v[:claim_paid][:value] * -1 }.to_json %>" ></canvas>
        </div>
      </div>
      <div class="card-chart">
        <div class="card-chart-text">
          Claims & Reserves Change
          <canvas id="claimsAndRes" width="400" height="400" data-years="<%= @data_process.map { |k, v| k  }.sort.to_json %>" data-process-json="<%= @data_process.map{ |k, v| v[:claim_paid_and_reserves_change][:value] * -1 }.to_json %>"></canvas>
        </div>
      </div>
    </div>
  </div>      <!-- Create an element where the map will take place -->
</div>

app/views/shared/_container_dashboard_commissions.html.erb
<div class="container-dashboard" id="dashboard-area">
  <div class="container-top">
    <div class="container-left">
      <div class="card-survey">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

          <div class="card-chart-text">
          Satisfaction Survey
          </div>
          <% @select_countries.sort.each do |country| %>
            <% if @checked_values[:country].include?(country)  %>
              <div class="rating d-flex justify-content-between">
                <p><%= country %></p>
                <div class="score">
                  <% multiple = [1, 2, 3, 4, 5].sample %>
                  <% serieA = [1, 1, 1, 1, 1].sample(multiple) %>
                  <% serieA.each do |star| %>
                    <span class="fa fa-star checked"></span>
                    <% end %>
                  <% multiple_unstarred = 5 - multiple %>
                  <% serieB = [1, 1, 1, 1, 1].sample(multiple_unstarred) %>
                    <% serieB.each do |nostar| %>
                      <span class="fa fa-star"></span>
                    <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
      </div>
    </div>

    <div class="container-right  d-flex">
      <div class="card-chart">
        <div class="card-chart-text">
          Reinsurance Commissions
        </div>
          <canvas id="reinsComm" width="400" height="400" data-countries="<%= @data_process.map { |k, v| k  }.to_json %>" data-process-json="<%= @data_process.map{ |k, v| v[:reins_comm_ratio] * -1 }.to_json %>"></canvas>
      </div>
      <div class="card-chart">
        <div class="card-chart-text">
          Broker Commissions
        </div>
          <canvas id="brokerComm" width="400" height="400" data-countries="<%= @data_process.map { |k, v| k  }.to_json %>" data-process-json="<%= @data_process.map{ |k, v| v[:broker_comm_ratio] * -1  }.to_json %>"></canvas>
      </div>
    </div>
  </div>      <!-- Create an element where the map will take place -->
</div>

app/views/shared/_container_dashboard_notes.html.erb
<div class="container-dashboard" id="dashboard-area">
  <div class="container-top">
    <div class="container-left">
      <div class="card-survey">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <div class="card-chart-text">
          <%= render 'shared/note' %>
        </div>
      </div>
    </div>
    <div class="container-right  d-flex">
      <div class="container-table">
        <div class="card-table">
          <table style="width:100%">
            <tr class="col-name">
              <th>Due Date</th>
              <th>Note</th>
              <th>Priority</th>
              <th>Status</th>
              <th>Update</th>
              <th>Delete</th>
              <!--EVENTUALLY TO INTEGRATE LATER ON
<th>User</th>
<th>Assigned to</th> -->
            </tr>
            <% @notes.each do |n|%>

              <tr>
                <td class="note-due-date"><%= n.due_date %></td>
                <td class="note-priority"><%= n.priority %></td>
                <td class="note-content"><%= n.comment %></td>
                <td><i class="far fa-pause-circle"></i></td>
              <td><i class="far fa-edit" id="update-icon"></i></td>
              <td><i class="far fa-trash-alt" id="delete-icon"></i></td>
              </tr>
            <% end %>
<!--               <td class="note-due-date">20/01/2020</td>
              <td class="note-priority">High</td>
              <td class="note-content">Bellis incursare per et si rege ordinatus versabili ordinatus inligato aliquotiens hostiliter a sollicite nostra si a locum bellis bellis rege ordinatus sollicite nos Nohodares in numero sollicite rege explorabat adducta Mesopotamiam adducta conlimitiis Persarum copia Mesopotamiam aliquotiens bellis eum usquam perrupturus quae adducta gentes moventem e finitimis dederit Mesopotamiam dederit nomine si quae conlimitiis nos saepe iuvant vi per iuvant nostra sollicite quadam arma nos et perrupturus quotiens re usquam quae incessunt locum Mesopotamiam repellenteque Mesopotamiam saepe quae bellis nomine in aliquotiens Persarum mente repellenteque quadam incessunt numero incessunt sollicite adducta mente arma et perrupturus perrupturus si sollicite sollicite.</td>
              <td><i class="far fa-pause-circle"></i></td>
              <td><i class="far fa-edit"></i></td>
              <td><i class="far fa-trash-alt"></i></td> -->
<!--             <tr>
              <td class="note-due-date">07/02/2020</td>
              <td class="note-priority">Medium</td>
              <td class="note-content">Eminuit autem inter humilia supergressa iam impotentia fines mediocrium delictorum nefanda Clematii cuiusdam Alexandrini nobilis mors repentina; cuius socrus cum misceri sibi generum, flagrans eius amore, non impetraret, ut ferebatur, per palatii pseudothyrum introducta, oblato pretioso reginae monili id adsecuta est, ut ad Honoratum tum comitem orientis formula missa letali omnino scelere nullo contactus idem Clematius nec hiscere nec loqui permissus occideretur. Quod si rectum statuerimus vel concedere amicis, quidquid velint, vel impetrare ab iis, quidquid velimus, perfecta quidem sapientia si simus, nihil habeat res vitii; sed loquimur de iis amicis qui ante oculos sunt, quos vidimus aut de quibus memoriam accepimus, quos novit vita communis. Ex hoc numero nobis exempla sumenda sunt, et eorum quidem maxime qui ad sapientiam proxime accedunt. Proinde die funestis interrogationibus praestituto imaginarius iudex equitum resedit magister adhibitis aliis iam quae essent agenda praedoctis, et adsistebant hinc inde notarii, quid quaesitum esset, quidve responsum, cursim ad Caesarem perferentes, cuius imperio truci, stimulis reginae exsertantis aurem subinde per aulaeum, nec diluere obiecta permissi nec defensi periere conplures.</td>
              <td><i class="far fa-play-circle"></i></td>
              <td><i class="far fa-edit"></i></td>
              <td><i class="far fa-trash-alt"></i></td>
            </tr>
            <tr>
              <td class="note-due-date">07/10/2019</td>
              <td class="note-priority">Low</td>
              <td class="note-content">Ipsum Catoni laudantur Catoni laudantur ne sic anteponas istum iudicavit ut quem sic sic sapientissimum illius loquar De Catoni ut autem enim habetote De ipsum sapientissimum cum istum ais rem utroque dicta ob sapientissimum Catoni anteponas ipsum habetote autem ne quem anteponas loquar sic rem sapientissimum vestrum loquar huius rem De quem utroque ais habetote huius laudantur habetote ut De ais ut ipsum anteponas iam sapientissimum quidem sic laudantur De autem laudantur cum vestrum ob ob loquar utroque quem ipsum iam De vestrum sic loquar utroque habetote me habetote huius Apollo facta illius enim ut ob utroque istum autem illius.</td>
              <td><i class="far fa-check-circle"></i></td>
              <td><i class="far fa-edit"></i></td>
              <td><i class="far fa-trash-alt"></i></td>
            </tr> -->
          </table>
        </div>
      </div>
    </div>
  </div>      <!-- Create an element where the map will take place -->
</div>

app/views/shared/_container_dashboard_renewals.html.erb
<div class="renewal-chart">
  <div id="chart">
  </div>
    <div id="combined-chart">
  </div>
</div>

app/views/shared/_container_dashboard_rfps.html.erb
in this page we shall integrate the
CAGR
the possibility to filter by contract,
line of risk
country,
local insurer
renewal

we w

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.linkedin.com/company/fenix-analytics"><i class="fab fa-linkedin"></i></a>
<!--     <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a> -->
    <a href="mailto:vanderkelen@fenix-analytics.com"><i class="far fa-envelope"></i></a>
  </div>
<!--     <div class="fenix-info">
    <h3>Fenix Consulting -  </h3>
    <p>55, Terkluizendreef    1640 - Sint-Genesius-Rode (BE)</p>
    <p><i class="fas fa-phone-alt"></i>+32-474/91.81.44  <i class="fas fa-at"></i>info@fenix.com</p>
  </div> -->
  <div class="footer-copyright text-responsive">
    <!-- ©  -->Fenix Analytics B.V., 2020
  </div>
</div>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-fenix" id="navbar" data-spy="scroll" data-target=".navbar-fenix" data-offset="50">
  <%= link_to pages_path, class: "navbar-brand" do %>
    <h2><%= image_tag "logo_navbar.png" %> </h2>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<% url = request.original_url  %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>


<!-- BE CAREFULL the url.gsub is a quick fix to move to other pages! make sure this is correct to always redirect to pages! -->


        <li class="nav-item d-flex align-items-center">
          <% if url.include?("pages") %>
            <%= link_to "Commissions", url.gsub("pages", "commissions"), class: "nav-link" %>
          <% elsif url.include?("notes") %>
            <%= link_to "Commissions", url.gsub("notes", "commissions"), class: "nav-link" %>
          <% else %>
            <%= link_to "Commissions", url.gsub("claims", "commissions"), class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item active d-flex align-items-center">
          <% if url.include?("pages") %>
            <%= link_to "Claims", url.gsub("pages", "claims"), class: "nav-link" %>
          <% elsif url.include?("notes") %>
            <%= link_to "Claims", url.gsub("notes", "claims"), class: "nav-link" %>
          <% else %>
            <%= link_to "Claims", url.gsub("commissions", "claims"), class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item active d-flex align-items-center">
          <% if url.include?("pages") %>
            <%= link_to "Renewals", url.gsub("pages", "renewals"), class: "nav-link" %>
          <% elsif url.include?("commissions") %>
            <%= link_to "Renewals", url.gsub("commissions", "renewals"), class: "nav-link" %>
          <% elsif url.include?("commissions") %>
            <%= link_to "Renewals", url.gsub("claims", "renewals"), class: "nav-link" %>
          <% else %>
            <%= link_to "Renewals", url.gsub("notes", "renewals"), class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item d-flex align-items-center">
          <%= link_to "Reserves", pages_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-flex align-items-center">
          <% if url.include?("pages") %>
            <%= link_to "Notes", url.gsub("pages", "notes"), class: "nav-link" %>
          <% elsif url.include?("commissions") %>
            <%= link_to "Notes", url.gsub("commissions", "notes"), class: "nav-link" %>
          <% else %>
            <%= link_to "Notes", url.gsub("claims", "notes"), class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item active d-flex align-items-center">
          <%= link_to "Upload Data", new_file_upload_path, class: "nav-link" %>
        </li>
        <li class="nav-item active d-flex align-items-center">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <p class="d-flex align-items-center">Hi, <%= current_user.first_name %></p>
        <li class="nav-item dropdown">
          <% if !current_user.profile_picture %>
            <%= image_tag "placeholder.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= cl_image_tag current_user.profile_picture, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
<!--
!!!!!!! IT USED TO BE A DROPDOWN LIST LINKED TO THE AVATAR OF THE USER. HOWEVER THIS HAS BEEN BROKEN AND DOESN4T WORK ANYMORE.
AS AN ALTERNATIVE, FOR THE TIME BEING, BTN HAVE BEEN ADDED TO THE NAVBAR
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Upload Data", new_file_upload_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div> -->
        </li>
        <!--

         </li>-->
      <% else %>
<!--         <li class="nav-item d-flex align-items-center">
          <%= link_to "Consultant Hub", "#", class: "nav-link"  %>
        </li>
        <li class="nav-item d-flex align-items-center">
          <%= link_to "Learn More", "#", class: "nav-link"  %>
        </li>
        <li class="nav-item d-flex align-items-center">
          <%= link_to "Book a Demo", "#", class: "nav-link"  %>
        </li>-->
        <li class="nav-item d-flex align-items-center">
         <%= link_to "About Fenix", "#about", class: "nav-link"  %>
        </li>
        <li class="nav-item d-flex align-items-center">
          <%= link_to "Our Services", "#services", class: "nav-link"  %>
        </li>
        <!-- <li class="nav-item d-flex align-items-center">
          <%= link_to "Our Product", "#product", class: "nav-link"  %>
        </li>-->
<!--         <li class="nav-item d-flex align-items-center">
          <%= link_to "Consultant Hub", "#", class: "nav-link"  %>
        </li> -->
        <li class="nav-item d-flex align-items-center">
          <%= link_to "Contact", "#contact", class: "nav-link"  %>
        </li>
        <li> <%= link_to "Dashboard", new_user_session_path, class: "nav-link" %>  </li>
        </ul>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_note.html.erb
<strong>Add A Note</strong>
<div>
  <div class="card-notes-structure">
    <%= simple_form_for(Note.new) do |f| %>
      <div class='comments-area d-flex justify-content-around w-100'>
        <%= f.input :comment %>
      </div>
      <div class="radio-btn d-flex justify-content-around">
        <div>
          <%= f.input :priority, as: :radio_buttons, collection: ['High', 'Medium', 'Low'] %>
        </div>
        <div>
          <%= f.input :status, as: :radio_buttons, collection: ['Closed', 'In Progress', 'Pending']  %>
        </div>
      </div>
      <div>
        <%= f.input :due_date %>
      </div>
      <%= f.button :submit, "Save Note", class: "btn btn-yellow", data: { confirm: 'Your note has been saved' }%>
    <% end %>
  </div>
</div>

<!-- THE ONE WORKING PROPERLY BUT NOT STORING INFO -->
<!-- <strong>Add A Note</strong>
< div>
  <form>
    <div class="card-notes-structure">
      <div class='comments-area d-flex justify-content-around w-100'>
        <textarea class="text-area" name="message" rows="10" cols="30" maxlength="700" width="90%"></textarea>
      </div>
      <div class="radio-btn d-flex justify-content-around">
        <div>
          <strong>Priority:</strong><br>
          <input type="radio" name="priority" value="high"> High<br>
          <input type="radio" name="priority" value="medium"> Medium<br>
          <input type="radio" name="priority" value="low" checked> Low<br>
        </div>
        <div>
          <strong>Status:</strong><br>
          <input type="radio" name="status" value="closed"> Closed<br>
          <input type="radio" name="status" value="in_progress"> In Progress<br>
          <input type="radio" name="status" value="pending" checked> Pending<br>
        </div>
      </div>
      <div class="deadline-and-submission">
        <div>
          <strong>Due by:</strong>
          <input type="date" name="deadline">
        </div>
        <input type="submit" value="Save">
      </div>
    </div>
  </form>
</div>


 -->

app/views/shared/_sidebar.html.erb
<div class="sidebar-main open" id="sidebar-main-js">

    <a href="javascript:void(0)" class="closebtn" id="close-sidebar-btn-js">
      <i id="icon" class="fas fa-angle-double-left"></i>
    </a>

    <form>
      <p class="filter">Balance Year</p>
        <% @select_years.sort.each do |year| %>
          <% checked = @checked_values[:balance_year].include?(year.to_s)  %>
          <li class="filter"><%= check_box_tag "balance_year[#{year}]", year, checked %>
          <%= label_tag year %></li>
        <% end %>

      <p class="filter">Countries</p>
      <% @select_countries.sort.each do |country| %>
        <% checked = @checked_values[:country].include?(country)  %>
          <li class="filter"><%= check_box_tag "country[#{country}]", country, checked %>
          <%= label_tag country %></li>
         <% end %>

        <p class="filter">Risks</p>
        <% @select_risks.sort.each do |risk| %>
          <% checked = @checked_values[:risk].include?(risk)  %>
          <li class="filter"><%= check_box_tag "risk[#{risk}]", risk, checked %>
          <%= label_tag risk %></li>
        <% end %>

      <p><input type="submit" value="Filter" class="btn btn-blue filter"></p>
    </form>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle btn btn-yellow mail-to-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Email Team</a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% all_team = User.all.where("id != ?", current_user.id) %>
        <% team = all_team.where("international_client_id = #{current_user.international_client_id}") %>
        <% team.each do |member| %>
          <%= button_to "#{member.first_name}", share_page_with_options_pages_path(user_id: member.id, shared_url: request.original_url, remote: true, method: :post), class: "btn-turquoise", data: {toggle: "modal", target: "#exampleModalCenter"} %>
        <% end %>
      </div>
  </li>

    <a href="javascript:void(0)" class="closebtn" id="close-sidebar-btn-js-bottom">
      <i id="icon-bottom" class="fas fa-angle-double-left"></i>
    </a>

</div>

<!--
   <p class="filter">Networks</p>
        <% @select_networks.sort.each do |network| %>
          <% checked = @checked_values[:reinsurance_network].include?(network)  %>
          <li class="filter"><%= check_box_tag "network[#{network}]", network, checked %>
          <%= label_tag network %></li>
        <% end %>
    <ul>Local Insurers
      <% @select_local_insurers.each do |li| %>
        <li><%= check_box_tag "li[#{li}]", li %>
          <%= label_tag li %></li>
      <% end %>
    </ul>
    <ul>Geo Area
      <% @select_geo_area.each do |ga| %>
        <li><%= check_box_tag "ga[#{ga}]", ga %>
          <%= label_tag ga %></li>
      <% end %>
    </ul>
    <ul>Business Div
      <% @select_business_div.each do |bd| %>
        <li><%= check_box_tag "bd[#{bd}]", bd %>
          <%= label_tag bd %></li>
      <% end %>
    </ul>
    <ul>Local Client
      <% @select_local_clients.each do |lc| %>
        <li><%= check_box_tag "lc[#{lc}]", lc %>
          <%= label_tag lc %></li>
      <% end %>
    </ul>
    <ul>Quarter
      <% @select_quarter.each do |q| %>
        <li><%= check_box_tag "q[#{q}]", q %>
          <%= label_tag q %></li>
      <% end %> -->
 <!--    </ul> -->



<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Success!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <strong>EMAIL SUCCESSFULLY SENT !</strong>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>